using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InstallmentSystem.Data;
using InstallmentSystem.DTOs;
using InstallmentSystem.Models;
using InstallmentSystem.Models.Enums;
using Microsoft.AspNetCore.Authorization;
using InstallmentSystem.Authorization;

namespace InstallmentSystem.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class JournalController : ControllerBase
{
    private readonly AppDbContext _db;
    public JournalController(AppDbContext db) => _db = db;

    [HttpGet]
    [HasPermission("Journal.Read")]
    public async Task<IActionResult> GetAll(
        [FromQuery] DateTime? from,
        [FromQuery] DateTime? to,
        [FromQuery] JournalEntryType? type)
    {
        var query = _db.JournalEntries
            .Include(j => j.Details).ThenInclude(d => d.Account)
            .Include(j => j.Receipt)
            .Include(j => j.Currency)
            .AsQueryable();

        if (from.HasValue) query = query.Where(j => j.EntryDate >= from.Value);
        if (to.HasValue)   query = query.Where(j => j.EntryDate <= to.Value);
        if (type.HasValue) query = query.Where(j => j.Type == type.Value);

        var entries = await query
            .OrderByDescending(j => j.EntryDate)
            .Select(j => new {
                j.Id, j.EntryNumber, j.EntryDate, j.Description,
                j.Type, j.IsReversed,
                j.ExchangeRate,
                CurrencyName  = j.Currency != null ? j.Currency.Name : null,
                CurrencyCode  = j.Currency != null ? j.Currency.Code : null,
                CurrencySymbol= j.Currency != null ? j.Currency.Symbol : null,
                ReceiptNumber = j.Receipt != null ? j.Receipt.ReceiptNumber : null,
                TotalDebit    = j.Details.Sum(d => d.Debit),
                TotalCredit   = j.Details.Sum(d => d.Credit),
                IsAutoGenerated = j.ReceiptId != null || j.Type == JournalEntryType.ContractIssue || j.Type == JournalEntryType.Cancel,
                Details       = j.Details.Select(d => new {
                    d.Id, d.Debit, d.Credit,
                    AccountName = d.Account.Name,
                    AccountType = d.Account.Type
                })
            }).ToListAsync();

        return Ok(entries);
    }

    [HttpGet("{id}")]
    [HasPermission("Journal.Read")]
    public async Task<IActionResult> GetById(Guid id)
    {
        var entry = await _db.JournalEntries
            .Include(j => j.Details).ThenInclude(d => d.Account)
            .Include(j => j.Receipt).ThenInclude(r => r!.Customer)
            .Include(j => j.Currency)
            .FirstOrDefaultAsync(j => j.Id == id);

        return entry == null ? NotFound() : Ok(entry);
    }

    [HttpPost]
    [HasPermission("Journal.Create")]
    public async Task<IActionResult> Create([FromBody] CreateJournalEntryDto dto)
    {
        var totalDebit  = dto.Details.Sum(d => d.Debit);
        var totalCredit = dto.Details.Sum(d => d.Credit);

        if (Math.Abs(totalDebit - totalCredit) > 0.01m)
            return BadRequest(new { message = "مجموع المدين يجب أن يساوي مجموع الدائن" });

        var currency = dto.CurrencyId.HasValue 
            ? await _db.Currencies.FindAsync(dto.CurrencyId.Value)
            : await _db.Currencies.FirstOrDefaultAsync(c => c.IsBase);

        var entry = new JournalEntry
        {
            EntryNumber = $"JNL-{DateTime.UtcNow:yyyyMMddHHmmss}",
            EntryDate   = dto.EntryDate,
            Description = dto.Description,
            Type        = dto.Type,
            CurrencyId  = currency?.Id,
            ExchangeRate= dto.ExchangeRate ?? currency?.ExchangeRate ?? 1,
            Details     = dto.Details.Select(d => new JournalEntryDetail
            {
                AccountId = d.AccountId,
                Debit     = d.Debit,
                Credit    = d.Credit
            }).ToList()
        };

        _db.JournalEntries.Add(entry);
        await _db.SaveChangesAsync();
        return CreatedAtAction(nameof(GetById), new { id = entry.Id }, entry);
    }

    [HttpPut("{id}")]
    [HasPermission("Journal.Update")]
    public async Task<IActionResult> Update(Guid id, [FromBody] CreateJournalEntryDto dto)
    {
        var entry = await _db.JournalEntries.Include(j => j.Details).FirstOrDefaultAsync(j => j.Id == id);
        if (entry == null) return NotFound();

        // منع تعديل القيود المولدة آلياً
        bool isAuto = entry.ReceiptId != null || entry.Type == JournalEntryType.ContractIssue || entry.Type == JournalEntryType.Cancel;
        if (isAuto)
            return BadRequest(new { message = "لا يمكن تعديل القيود المولدة آلياً من النظام." });

        var totalDebit  = dto.Details.Sum(d => d.Debit);
        var totalCredit = dto.Details.Sum(d => d.Credit);

        if (Math.Abs(totalDebit - totalCredit) > 0.01m)
            return BadRequest(new { message = "مجموع المدين يجب أن يساوي مجموع الدائن" });

        var currency = dto.CurrencyId.HasValue 
            ? await _db.Currencies.FindAsync(dto.CurrencyId.Value)
            : await _db.Currencies.FirstOrDefaultAsync(c => c.IsBase);

        // Update properties
        entry.EntryDate   = dto.EntryDate;
        entry.Description = dto.Description;
        entry.CurrencyId  = currency?.Id;
        entry.ExchangeRate= dto.ExchangeRate ?? currency?.ExchangeRate ?? 1;

        // Clear and rebuild details
        _db.JournalEntryDetails.RemoveRange(entry.Details);
        entry.Details = dto.Details.Select(d => new JournalEntryDetail
        {
            AccountId = d.AccountId,
            Debit     = d.Debit,
            Credit    = d.Credit
        }).ToList();

        await _db.SaveChangesAsync();
        return Ok(new { message = "تم تحديث القيد بنجاح" });
    }

    [HttpDelete("{id}")]
    [HasPermission("Journal.Delete")]
    public async Task<IActionResult> Delete(Guid id)
    {
        var entry = await _db.JournalEntries.Include(j => j.Details).FirstOrDefaultAsync(j => j.Id == id);
        if (entry == null) return NotFound();

        bool isAuto = entry.ReceiptId != null || entry.Type == JournalEntryType.ContractIssue || entry.Type == JournalEntryType.Cancel;
        if (isAuto)
            return BadRequest(new { message = "لا يمكن حذف القيود المولدة آلياً لسلامة النظام المحاسبي." });

        _db.JournalEntries.Remove(entry);
        await _db.SaveChangesAsync();
        return Ok(new { message = "تم حذف القيد بنجاح" });
    }

    [HttpGet("accounts")]
    public async Task<IActionResult> GetAccounts() =>
        Ok(await _db.Accounts
            .Include(a => a.Children)
            .Where(a => a.ParentId == null)
            .ToListAsync());

    [HttpGet("trial-balance")]
    public async Task<IActionResult> GetTrialBalance()
    {
        var balance = await _db.Accounts
            .Include(a => a.JournalEntryDetails)
            .Select(a => new {
                a.Id, a.Name, a.Type,
                TotalDebit  = a.JournalEntryDetails.Sum(d => d.Debit),
                TotalCredit = a.JournalEntryDetails.Sum(d => d.Credit),
                Balance     = a.JournalEntryDetails.Sum(d => d.Debit) -
                              a.JournalEntryDetails.Sum(d => d.Credit)
            })
            .Where(a => a.TotalDebit > 0 || a.TotalCredit > 0)
            .ToListAsync();

        return Ok(balance);
    }
}
